FROM microsoft/nanoserver:1803
LABEL maintainer "Gamal Abdul Nasser <gamalanpro@gmail.com>"

EXPOSE 80 443 2015

COPY artifacts/binaries/windows/amd64/caddy.exe "C:\\caddy.exe"

ENTRYPOINT ["C:\\caddy.exe"]