FROM microsoft/nanoserver:1803 as nanoserver

RUN curl https://getcaddy.com | bash -s personal docker,http.cache,http.locale,http.minify,http.prometheus,http.proxyprotocol,http.ratelimit,http.realip,http.reauth,http.s3browser,tls.dns.cloudflare,tls.dns.digitalocean,tls.dns.namecheap

#FROM microsoft/nanoserver:1803
#LABEL maintainer "Gamal Abdul Nasser <gamalanpro@gmail.com>"
#EXPOSE 80 443 2015

#COPY artifacts/binaries/windows/amd64/caddy.exe "C:\\caddy.exe"

#ENTRYPOINT ["C:\\caddy.exe"]